version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-go"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gcq4hy1vk2az"
s3_prefix = "lambda-go"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
