# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: productinfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11productinfo.proto\x12\tecommerce\"#\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1a\n\tProductID\x12\r\n\x05value\x18\x01 \x01(\t2\x81\x01\n\x0bProductInfo\x12\x38\n\naddProduct\x12\x12.ecommerce.Product\x1a\x14.ecommerce.ProductID\"\x00\x12\x38\n\ngetProduct\x12\x14.ecommerce.ProductID\x1a\x12.ecommerce.Product\"\x00\x62\x06proto3')



_PRODUCT = DESCRIPTOR.message_types_by_name['Product']
_PRODUCTID = DESCRIPTOR.message_types_by_name['ProductID']
Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'productinfo_pb2'
  # @@protoc_insertion_point(class_scope:ecommerce.Product)
  })
_sym_db.RegisterMessage(Product)

ProductID = _reflection.GeneratedProtocolMessageType('ProductID', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTID,
  '__module__' : 'productinfo_pb2'
  # @@protoc_insertion_point(class_scope:ecommerce.ProductID)
  })
_sym_db.RegisterMessage(ProductID)

_PRODUCTINFO = DESCRIPTOR.services_by_name['ProductInfo']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCT._serialized_start=32
  _PRODUCT._serialized_end=67
  _PRODUCTID._serialized_start=69
  _PRODUCTID._serialized_end=95
  _PRODUCTINFO._serialized_start=98
  _PRODUCTINFO._serialized_end=227
# @@protoc_insertion_point(module_scope)
