# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ordermanagement.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15ordermanagement.proto\x12\tecommerce\x1a\x1egoogle/protobuf/wrappers.proto\"[\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05items\x18\x02 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x13\n\x0b\x64\x65stination\x18\x05 \x01(\t2O\n\x0fOrderManagement\x12<\n\x08GetOrder\x12\x1c.google.protobuf.StringValue\x1a\x10.ecommerce.Order\"\x00\x62\x06proto3')



_ORDER = DESCRIPTOR.message_types_by_name['Order']
Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), {
  'DESCRIPTOR' : _ORDER,
  '__module__' : 'ordermanagement_pb2'
  # @@protoc_insertion_point(class_scope:ecommerce.Order)
  })
_sym_db.RegisterMessage(Order)

_ORDERMANAGEMENT = DESCRIPTOR.services_by_name['OrderManagement']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORDER._serialized_start=68
  _ORDER._serialized_end=159
  _ORDERMANAGEMENT._serialized_start=161
  _ORDERMANAGEMENT._serialized_end=240
# @@protoc_insertion_point(module_scope)
